# Chapter 3 - Introduction to neural prediction: forward propagation
-------

## Your first neural network

A neural network simply takes in some piece of data with a weight (or weights) attached, performs some mathmatical operation with them and returns a prediction.

In [2]:
weight = 0.1
def neural_network(input, weight):
    prediction = input * weight
    return prediction

number_of_toes = [8.5, 9.5, 10, 9]
input = number_of_toes[0]

pred = neural_network(input, weight)
print(pred)

0.8500000000000001


## A neural network with multiple inputs

In [4]:
def w_sum(a,b):
    assert(len(a) == len(b))
    output = 0
    for i in range(len(a)):
        output += (a[i] * b[i])
    return output

weights = [0.1, 0.2, 0]
def neural_network(input, weight):
    prediction = w_sum(input,weight)
    return prediction

toes = [8.5, 9.5, 9.9, 9.0]
wlrec = [0.65, 0.8, 0.8, 0.9]
nfans = [1.2, 1.3, 0.5, 1.0]

input = [toes[0], wlrec[0], nfans[0]]

pred = neural_network(input, weights)
print(pred)

0.9800000000000001


This neural network multiplies 3 input values by their corresponding weights, creating a weighted sum. The weighted sum is actually a dot product of the two vectors
input and weights.

### Using numpy

In [2]:
import numpy as np

def neural_network(input, weights) -> float:
    prediction = input.dot(weights)
    return prediction

weights = np.array([0.1, 0.2, 0])
toes = np.array([8.5, 9.5, 9.9, 9.0])
wlrec = np.array([0.65, 0.8, 0.8, 0.9])
nfans = np.array([1.2, 1.3, 0.5, 1.0])

input = np.array([toes[0], wlrec[0], nfans[0]])

pred = neural_network(input, weights)
print(pred)

0.9800000000000001


## A Neural Network with multiple outputs

This neural network makes 3 separate predictions that act like 3 separate single-weight neural networks.

It predicts not just if the team won or lost but also if the players are happy or sad and are they hurt.

In [1]:
def ele_mul(scalar, vector):
    output = [0, 0, 0]

    assert(len(output) == len(vector))

    for i in range(len(vector)):
        output[i] = scalar * vector[i]

    return output

def neural_network(input, weights):
    pred = ele_mul(input, weights) # scalar multiplication
    return pred

weights = [0.3, 0.2, 0.9]
wlrec = [0.65, 0.8, 0.8, 0.9]
input = wlrec[0]

pred =  neural_network(input, weights)
print(pred)

[0.195, 0.13, 0.5850000000000001]


### Using numpy

In [2]:
import numpy as np

def neural_network(input, weights):
    pred = input * weights
    return pred

weights = np.array([0.3, 0.2, 0.9])
wlrec = np.array([0.65, 0.8, 0.8, 0.9])
input = wlrec[0]

pred =  neural_network(input, weights)
print(pred)

[0.195 0.13  0.585]


## Neural Networks with multiple inputs and multiple outputs

Both of the above ways can be combined to build a neural network that takes in multiple inputs and produces multiple outputs (predictions)

In [4]:
def w_sum(a,b):
    assert(len(a) == len(b))
    output = 0
    for i in range(len(a)):
        output += (a[i] * b[i])
    return output

def vect_mat_mul(vect, matrix):
    assert(len(vect) == len(matrix))
    output = [0, 0, 0]

    for i in range(len(vect)):
        output[i] = w_sum(vect, matrix[i])

    return output

def neural_network(input, weights):
    pred = vect_mat_mul(input, weights)

    return pred

weights = [
    #toes, win, fans
    [0.1, 0.1, -0.3], #hurt?
    [0.1, 0.2, 0.0], # won?
    [0.0, 1.3, 0.1], # sad?
]

toes = [8.5, 9.5, 9.9, 9.0]
wlrec = [0.65, 0.8, 0.8, 0.9]
nfans = [1.2, 1.3, 0.5, 1.0]

input = [toes[0], wlrec[0], nfans[0]]

pred = neural_network(input, weights)
print(pred)

[0.555, 0.9800000000000001, 0.9650000000000001]


### Using numpy

In [15]:
import numpy as np

def vect_mat_mul(vect, matrix):
    assert(len(vect) == len(matrix))
    output = [0, 0, 0]

    for i in range(len(vect)):
        output[i] = vect.dot(matrix[i])

    return output

def neural_network(input, weights):
    pred = vect_mat_mul(input, weights)

    return pred

weights = np.array([
    #toes, win, fans
    np.array([0.1, 0.1, -0.3]), #hurt?
    np.array([0.1, 0.2, 0.0]), # won?
    np.array([0.0, 1.3, 0.1]), # sad?
])

toes = np.array([8.5, 9.5, 9.9, 9.0])
wlrec = np.array([0.65, 0.8, 0.8, 0.9])
nfans = np.array([1.2, 1.3, 0.5, 1.0])

input = np.array([toes[0], wlrec[0], nfans[0]])
input_matrix = np.array([toes, wlrec, nfans])

pred = neural_network(input, weights)
print(pred)

# The easy way to do this...
print(input@weights.T)
print(input_matrix.T@weights.T)

[0.555, 0.9800000000000001, 0.9650000000000001]
[0.555 0.98  0.965]
[[0.555 0.98  0.965]
 [0.64  1.11  1.17 ]
 [0.92  1.15  1.09 ]
 [0.69  1.08  1.27 ]]


## Predicting on Predictions
-----
### Neural networks can be stacked!

You can take the output of one network and feed it as input to another network. This results in two consecutive vector-matrix multiplications.

In [16]:
import numpy as np

ih_wgt = np.array([
              # toes % win # fans
              [0.1, 0.2,-0.1],   # hid[0]
              [-0.1,0.1,0.9],    # hid[1]
              [0.1, 0.4,0.1]]).T # hid[2]

hp_wgt = np.array([
              # hid[0] hid[1] hid[2]
            [0.3, 1.1, -0.3],    # hurt?
            [0.1, 0.2, 0.0],     # win? 
            [0.0, 1.3, 0.1] ]).T # sad?

weights = [ih_wgt, hp_wgt]

def neural_network(input, weights):
    hid = input.dot(weights[0]) 
    pred = hid.dot(weights[1]) 
    return pred
    
toes = np.array([8.5, 9.5, 9.9, 9.0]) 
wlrec = np.array([0.65,0.8, 0.8, 0.9]) 
nfans = np.array([1.2, 1.3, 0.5, 1.0])

input = np.array([toes[0],wlrec[0],nfans[0]])

pred = neural_network(input,weights) 
print(pred)

[0.2135 0.145  0.5065]


## A Primer on Numpy
-----

In [19]:
import numpy as np

a = np.array([0,1,2,3]) # A vector (1x4 matrix)
b = np.array([4,5,6,7]) # Another vector (1x4 matrix)
c = np.array([[0,1,2,3],
             [4,5,6,7]]) # A 2x4 matrix

d = np.zeros((2,4))      # A 2x4 matrix of zeroes
e = np.random.rand(2,5)  # A 2x5 matrix of random numbers between 0 and 1

print(a)
print(b)
print(c)
print(d)
print(e)


print(2 * a)    # Scalar multiplication
print(a * b)    # Elementwise multiplication between a and b

print(a * b * 2)  # Elementwise multiplication followed by a scalar multiplication

print(a * c)      # Elementwise multiplication on every row of matrix c. The number of columns of a and c MUST be equal.

print(a * e)      # This throws a ValueError because the columns ARE NOT equal.

[0 1 2 3]
[4 5 6 7]
[[0 1 2 3]
 [4 5 6 7]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0.1160241  0.99505324 0.69125262 0.35971728 0.04399064]
 [0.97598944 0.94230765 0.05596662 0.57795291 0.10725119]]
[0 2 4 6]
[ 0  5 12 21]
[ 0 10 24 42]
[[ 0  1  4  9]
 [ 0  5 12 21]]


ValueError: operands could not be broadcast together with shapes (4,) (2,5) 

In [ ]:
import numpy as np

a = np.zeroes( (1,4) )
b = np.zeroes( (4,3) )

c = a.dot(b) # The dot product is different than multiplication

print(c.shape)

In [23]:
print(2**2)
print(2**3)
print(2**(2+3))
print(2**(2*3))
print(2**(2**3))
print(2**8)

4
8
32
64
256
256
